# Generated by Django 4.2.7 on 2023-11-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_disgription_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
