# Generated by Django 5.0.3 on 2024-03-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_product_tags_delete_tag_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
