# Generated by Django 4.2.7 on 2024-08-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_orderedproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='total_price',
            new_name='total',
        ),
    ]
